version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80" # Map host port 8080 to container port 80
    volumes:
      - ./html:/usr/share/nginx/html:ro # Mount local directory for static files

